### ISSUE TITLE
OMERO.web prerequisites aren't updated on upgrades

### ISSUE THREAD

**Issue by kennethgillen** [openmicroscopy/prod-playbooks#118]
For some reason https://github.com/openmicroscopy/openmicroscopy/blob/v5.4.9/components/tools/OmeroWeb/requirements-py27-all.txt doesn't appear to be re-evaluated on OMERO.web upgrades for at least

- ome-demoserver.yml

This may well be an issue with https://github.com/openmicroscopy/ansible-role-omero-web rather than the "prod playbook", but at least a workaround can be written in this repo, and I'd class this repo as the place to leave a top-level issue with the config of a server defined here.

**Comment by manics** [comment]
What prerequisite wasn't upgraded?

**Comment by kennethgillen** [comment]
cf https://www.openmicroscopy.org/community/viewtopic.php?f=5&t=8606&p=20130#p20130

numpy

**Comment by manics** [comment]
https://github.com/openmicroscopy/ansible-role-omero-web/blob/2.0.1/tasks/web-install.yml#L122 uses https://github.com/openmicroscopy/openmicroscopy/blob/v5.4.9/components/tools/OmeroWeb/requirements-py27.txt since numpy and pillow are installed as operating system dependencies. AFAIK there's no need for the higher version of numpy in requirements-py27-all.txt
